version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=socialdb
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=admin
    ports:
      - 15432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
